### ISSUE TITLE
Can I know up to what laravel and elasticsearch version does this support?

### ISSUE THREAD

**Issue by yukari1414** [isswp101/elasticsearch-eloquent#20]
I'm using v5 for both and I see that this is using shift31 which if refer to the versioning [here](https://github.com/shift31/laravel-elasticsearch), v5.5 of shift31 is not released yet.

**Comment by isswp101** [comment]
@yukari1414 very soon I will release a new version which will not use any dependencies, except for the official elasticseach client

**Comment by isswp101** [comment]
@yukari1414 btw, you can try to use the latest version of `elastic/elasticsearch` dependency in your project and pass the elasticsearch client to your model.

```
$esclient = Elasticsearch\ClientBuilder::create()->setHosts(["localhost:9200"])->build();
```

Pass `$esclient` instead of `app(Client::class)` in the constructor of your models

**Comment by yukari1414** [comment]
ahh i see.. cool! thanks! :D

**Comment by yukari1414** [comment]
Can't install.. LOL

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - shift31/laravel-elasticsearch 2.0.5 requires elasticsearch/elasticsearch ~2.0 -> satisfiable by elasticsearch/elasticsearch[2.0.x-dev, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3, v2.0.0-beta4, v2.0.0-beta5, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.3.0] but these conflict with your requirements or minimum-stability.
    - shift31/laravel-elasticsearch 2.0.4 requires elasticsearch/elasticsearch ~2.0 -> satisfiable by elasticsearch/elasticsearch[2.0.x-dev, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3, v2.0.0-beta4, v2.0.0-beta5, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.3.0] but these conflict with your requirements or minimum-stability.
    - shift31/laravel-elasticsearch 2.0.3 requires elasticsearch/elasticsearch ~2.0 -> satisfiable by elasticsearch/elasticsearch[2.0.x-dev, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3, v2.0.0-beta4, v2.0.0-beta5, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.3.0] but these conflict with your requirements or minimum-stability.
    - shift31/laravel-elasticsearch 2.0.2 requires elasticsearch/elasticsearch ~2.0 -> satisfiable by elasticsearch/elasticsearch[2.0.x-dev, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3, v2.0.0-beta4, v2.0.0-beta5, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.3.0] but these conflict with your requirements or minimum-stability.
    - shift31/laravel-elasticsearch 2.0.1 requires elasticsearch/elasticsearch ~2.0 -> satisfiable by elasticsearch/elasticsearch[2.0.x-dev, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3, v2.0.0-beta4, v2.0.0-beta5, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.3.0] but these conflict with your requirements or minimum-stability.
    - shift31/laravel-elasticsearch 2.0 requires elasticsearch/elasticsearch ~2.0 -> satisfiable by elasticsearch/elasticsearch[2.0.x-dev, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3, v2.0.0-beta4, v2.0.0-beta5, v2.0.1, v2.0.2, v2.0.3, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.2.0, v2.2.1, v2.2.2, v2.2.3, v2.3.0] but these conflict with your requirements or minimum-stability.
    - isswp101/elasticsearch-eloquent 1.1.0 requires shift31/laravel-elasticsearch ^2.0 -> satisfiable by shift31/laravel-elasticsearch[2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - Installation request for isswp101/elasticsearch-eloquent ^1.1 -> satisfiable by isswp101/elasticsearch-eloquent[1.1.0].


Installation failed, reverting ./composer.json to its original content.`

May I know when you'll be releasing the new version?

**Comment by isswp101** [comment]
@yukari1414 I pushed a new branch https://github.com/isswp101/elasticsearch-eloquent/tree/feature/5.0-elasticsearch which allows you to use the latest elasticsearch client. In addition, I removed `shift31/laravel-elasticsearch` dependency. I've tested it with 5.2.2 version.
